const handler = async (Gurita, m) => {
    if (!m.isGroup) return Gurita.sendMessage(m.chat, {text: "hanya bisa digunakan di grup"})
    
function getRandom(arr) {
  const randomIndex = Math.floor(Math.random() * arr.length);
  return arr[randomIndex];
}

const dares = [
  // Kategori Easy & Fun (1-50)
  "Tirukan suara binatang favoritmu selama 30 detik",
  "Lakukan tiktok dance selama 1 menit",
  "Kirim pesan 'Aku mencintaimu' ke kontak ke-5 di ponselmu",
  "Ubah foto profil WhatsApp menjadi foto bayi selama 1 jam",
  "Telepon teman dan bernyanyi lagu selamat ulang tahun",
  "Makan snack tanpa menggunakan tangan",
  "Posting story Instagram dengan filter paling jelek",
  "Tirukan selebriti favoritmu",
  "Buat rap spontan tentang orang di sebelahmu",
  "Tari seperti hantu selama 2 menit",
  "Ucapkan alfabet terbalik",
  "Makan 1 sendok makan kecap/saus sambal",
  "Bicara dengan aksen asing selama 5 menit",
  "Jadi orang pertama yang bertepuk tangan di tempat sepi",
  "Pakai pakaian terbalik selama 10 menit",
  "Nyanyi lagu dengan mengganti semua lirik dengan 'meong'",
  "Selfie dengan ekspresi teraneh dan post ke story",
  "Berjalan seperti robot keliling ruangan",
  "Tebak umur semua orang di ruangan",
  "Buat puisi tentang sendal",
  "Tirukan iklan TV favorit masa kecil",
  "Bicara seperti bayi selama 3 menit",
  "Push up 10 kali",
  "Makan pisang dengan gaya sensual",
  "Nyanyi lagu daerah dengan gaya metal",
  "Foto close-up hidung dan post ke story",
  "Tulis nama sendiri dengan mulut di kertas",
  "Tari balet di tengah ruangan",
  "Baca pesan terakhir di WhatsApp dengan suara dramatis",
  "Pakai semua aksesoris yang kamu punya sekaligus",
  "Buat suara efek film horor",
  "Jalan jongkok keliling ruangan",
  "Nyanyi lagu pop dengan gaya opera",
  "Tebak karakter kartun dari suara yang dibuat teman",
  "Selfie dengan tanaman/pohon terdekat",
  "Baca cepat 5 kali 'ular melingkar di atas pagar'",
  "Tirukan supermodel catwalk",
  "Makan kerupuk tanpa menggunakan tangan",
  "Buat stand up comedy 1 menit",
  "Goyangkan telinga tanpa menyentuhnya",
  "Nyanyi lagu dengan hidung terjepit",
  "Foto gaya ala model tahun 80-an",
  "Lompat seperti kelinci selama 1 menit",
  "Baca koran/majalah dengan suara bergetar",
  "Tirukan suara mesin cuci",
  "Pakai kaus kaki di tangan selama 15 menit",
  "Nyanyi lagu kebangsakan dengan mata tertutup",
  "Buat review makanan tentang nasi putih",
  "Tari dengan mata tertutup",
  "Bicara sambil menahan kelereng di mulut",
  
  // Kategori Embarrassing & Funny (51-100)
  "Posting foto masa kecil terburuk di media sosial",
  "Telepon eks dan bilang salah sambung",
  "Makan bawang merah mentah",
  "Nyanyi lagu romantis ke bantal",
  "Buat video TikTok dance dengan kostum aneh",
  "Ganti nama panggilan di WhatsApp menjadi 'Sayangku' selama 1 hari",
  "Makan mie tanpa kuah dan tanpa sendok/garpu",
  "Tari di tengah jalan (aman) selama 1 menit",
  "Puji diri sendiri di depan cermin dengan lantang",
  "Makan nasi dengan saus coklat",
  "Foto selfie dengan toilet dan post ke story",
  "Bicara dengan aksen Jawa/Sunda/Batak selama 10 menit",
  "Tirukan gaya jalan orang di ruangan ini",
  "Makan es krim dengan mata tertutup",
  "Post status Facebook 'Aku sedang jatuh cinta' tanpa konteks",
  "Nyanyi lagu dangdut dengan gaya rock",
  "Pakai baju terbalik keluar rumah selama 5 menit",
  "Makan snack pedas level tertinggi yang tersedia",
  "Video call orang tua dengan filter kelinci",
  "Buat review produk sampo di kamar mandi",
  "Tari dengan sapu sebagai partner",
  "Makan pisang dengan kulitnya (kulit sedikit saja)",
  "Posting twit 'Aku alien dari planet Mars'",
  "Bicara dengan pantat selama 3 menit",
  "Foto close-up siku dan jadikan wallpaper ponsel",
  "Minum air dengan posisi kepala di bawah",
  "Tirukan gaya foto model majalah tua",
  "Makan nasi pakai tangan kiri (jika kidal, pakai kanan)",
  "Posting IG story 'Jual diri murah'",
  "Nyanyi lagu India dengan gerakan kepala",
  "Pakai lipstik/semerah merah jika laki-laki",
  "Makan cabai rawit utuh",
  "Video diri sendiri sedang menangis dramatis",
  "Tari seperti sedang hujan tanpa musik",
  "Minum kopi tanpa gula dan bilang 'enak sekali'",
  "Post status 'Mencari jodoh, syarat: bisa bernapas'",
  "Bicara seperti robot yang rusak",
  "Makan snack sambil berdiri satu kaki",
  "Foto dengan patung/ boneka terdekat",
  "Nyanyi lagu dengan suara terpesek-pesek",
  "Pakai topi dari koran bekas",
  "Minum air putih seperti anggur mahal",
  "Posting 'Aku hamil' di media sosial (lalu hapus setelah 5 menit)",
  "Tirukan gaya jalan model runway tapi di tanah berlumpur imajiner",
  "Makan biskuit dengan air mata bawang",
  "Video review sendal jepit",
  "Nyanyi lagu anak-anak dengan beatbox",
  "Pakai kaos inside out seharian",
  "Minum teh tanpa diaduk",
  "Posting foto makanan dengan caption puisi cinta",
  
  // Kategori Social Media & Technology (101-150)
  "Upload foto paspor/KTP di story (tutup data penting)",
  "Update status 'Menikah hari ini'",
  "Ganti foto profil dengan foto bersama orang random",
  "Posting foto makanan kemarin",
  "Live Instagram membaca buku dongeng",
  "Kirim pesan ke grup keluarga 'Aku dapat pacar baru'",
  "Update LinkedIn 'Sedang mencari kerja di NASA'",
  "Posting tweet dalam bahasa isyarat (salah)",
  "Upload video menyanyi lagu nasional dengan salah lirik",
  "Ganti nama WhatsApp menjadi 'Tuhan YME'",
  "Posting foto selfie dengan filter kakek-nenek",
  "Kirim voice note berisi tangisan palsu ke teman",
  "Update bio Instagram dengan quotes aneh",
  "Posting story tengah malam berisi teori konspirasi",
  "Ganti wallpaper ponsel dengan foto orang di sebelahmu",
  "Upload video tutorial makeup yang salah",
  "Kirim email ke diri sendiri berisi pengakuan dosa",
  "Posting foto landscape terbalik",
  "Update status 'Baru saja melahirkan' (untuk laki-laki)",
  "Live TikTok membaca koran dengan aksen alien",
  "Ganti ringtone jadi suara ayam berkokok",
  "Posting foto makanan basi",
  "Kirim pesan ke mantan 'Apa kabar?' lalu delete",
  "Update bio Twitter dengan link acak",
  "Upload video unboxing batu",
  "Posting story 'Jual ginjal'",
  "Ganti font ponsel jadi yang paling sulit dibaca",
  "Kirim sticker cinta ke 10 kontak random",
  "Update WhatsApp status dengan lirik lagu sedih",
  "Posting foto selfie dengan sayuran",
  "Live Instagram menonton catatan sekolah",
  "Ganti notification sound jadi suara kentut",
  "Upload video membaca puisi untuk AC",
  "Posting foto dengan caption panjang tanpa spasi",
  "Kirim email kerja dengan font Comic Sans",
  "Update Facebook relationship status ke 'complicated'",
  "Posting story memasak air",
  "Ganti tema ponsel jadi pink glitter",
  "Upload video tour kamar mandi",
  "Posting foto dokumen penting (tutup data)",
  "Kirim pesan 'SOS' ke grup kantor",
  "Update Instagram highlight dengan foto makanan 1 tahun lalu",
  "Posting tweet berisi alfabet acak",
  "Live Facebook membaca iklan koran",
  "Ganti alarm jadi suara teriakan",
  "Upload video review pensil",
  "Posting foto dengan filter yang membuatmu seperti hantu",
  "Kirim pesan voice 'halo' ke 5 kontak berbeda",
  "Update Tinder bio dengan 'mencari alien'",
  "Posting story membaca buku telepon",
  "Ganti email signature dengan quotes film kartun",
  
  // Kategori Physical & Action (151-200)
  "Lakukan plank selama 1 menit",
  "Jalan merangkak keliling rumah",
  "Push up dengan satu tangan 5 kali",
  "Lompat tali imajiner selama 2 menit",
  "Berdiri dengan satu kaki selama 3 menit",
  "Squat 20 kali",
  "Jalan seperti crab selama 1 menit",
  "Lakukan yoga pose teraneh yang kamu tahu",
  "Berlari di tempat selama 2 menit",
  "Angkat beban dengan botol air",
  "Lakukan breakdance move sederhana",
  "Jalan mundur keliling ruangan",
  "Lompat seperti katak 10 kali",
  "Berdiri dengan kepala di bawah (handstand dengan bantuan dinding)",
  "Lakukan gerakan senam SD",
  "Jalan seperti model dengan buku di kepala",
  "Lompat tinggi sambil berteriak 'yeehaw'",
  "Lakukan gerakan tinju imajiner",
  "Berdansa dengan kursi",
  "Jalan seperti zombie selama 1 menit",
  "Lompat ke samping seperti kepiting",
  "Berdiri sambil menyentuh jari kaki 15 kali",
  "Lakukan gerakan moonwalk",
  "Jalan seperti penari balet",
  "Lompat sambil memeluk lutut 10 kali",
  "Berdiri di atas satu kaki sambil menyanyi",
  "Lakukan gerakan angkat besi dengan bantal",
  "Jalan seperti ninja",
  "Lompat seperti kanguru",
  "Berdiri sambil memutar badan 10 kali lalu jalan lurus",
  "Lakukan gerakan renang di lantai",
  "Jalan seperti gajah",
  "Lompat dengan satu kaki 20 kali",
  "Berdansa salsa sendirian",
  "Lakukan gerakan capoeira dasar",
  "Jalan seperti robot yang kehabisan baterai",
  "Lompat sambil berputar 5 kali",
  "Berdiri menghadap dinding selama 2 menit",
  "Lakukan gerakan silat",
  "Jalan seperti patung yang hidup",
  "Lompat tinggi sambil tepuk tangan di atas kepala",
  "Berdansa dengan sapu",
  "Lakukan gerakan seperti burung terbang",
  "Jalan seperti astronot di bulan",
  "Lompat sambil menepuk paha",
  "Berdiri sambil menyentuh langit-langit",
  "Lakukan gerakan seperti ular",
  "Jalan seperti pencuri yang menyelinap",
  "Lompat seperti monyet",
  "Berdansa dengan bantal",
  
  // Kategori Food & Drink Challenges (201-250)
  "Makan nasi dengan saus strawberry",
  "Minum air dari gelas tanpa tangan",
  "Makan biskuit dengan saos sambal",
  "Minum kopi tanpa gula dan tanpa ekspresi",
  "Makan mie instan tanpa direbus (kering)",
  "Minum teh dengan garam",
  "Makan roti dengan kecap",
  "Minum air dari mangkuk seperti kucing",
  "Makan pisang dengan kulitnya 1 gigit",
  "Minum susu dengan cabe rawit",
  "Makan kerupuk dengan selai coklat",
  "Minum air putih seperti anggur mahal",
  "Makan nasi dengan mayonaise",
  "Minum jus tanpa menelan langsung",
  "Makan snack dengan mata tertutup",
  "Minum air dari botol tanpa menyentuhnya dengan tangan",
  "Makan bubur dengan tangan",
  "Minum kopi hitam tanpa ekspresi",
  "Makan coklat dengan bawang goreng",
  "Minum air dengan posisi terbalik",
  "Makan kue dengan sumpit",
  "Minum teh tawar 1 gelas penuh",
  "Makan nasi dengan madu",
  "Minum air dari gelas kaki",
  "Makan keripik dengan saus tiram",
  "Minum susu kedelai dengan ekspresi bahagia",
  "Makan roti dengan saus tomat dan sambal",
  "Minum air kelapa dengan gaya aristokrat",
  "Makan buah dengan kulitnya (apel/pear)",
  "Minum jahe tanpa gula",
  "Makan sayur tanpa nasi",
  "Minum air putih seperti sedang minum racun",
  "Makan nasi dengan kuah soto",
  "Minum yogurt tanpa sendok",
  "Makan telur mentah (jika aman)",
  "Minum air dengan sedotan terkecil",
  "Makan spaghetti dengan sumpit",
  "Minum kopi instan tanpa air panas",
  "Makan burger terbalik",
  "Minum teh dengan gula 5 sendok",
  "Makan pizza dari tengah",
  "Minum air dari gelas dengan hidung",
  "Makan salad tanpa dressing",
  "Minum susu dengan sedikit kecap",
  "Makan kacang dengan mata tertutup",
  "Minum air es sampai menggigil",
  "Makan nasi dengan bubuk cabe",
  "Minum air putih seperti wine tasting",
  "Makan bakso tanpa kuah",
  "Minum jus jeruk dengan garam",
  
  // Kategori Social Interaction (251-300)
  "Puji 3 orang di ruangan ini dengan tulus",
  "Telepon orang tuamu dan bilang 'Aku kangen'",
  "Minta tanda tangan ke orang asing (aman)",
  "Tawarkan pijatan bahu ke orang di sebelahmu",
  "Telepon teman dan berpura-pura sebagai sales",
  "Beri komplimen ke 5 orang di media sosial",
  "Minta selfie ke orang random (dengan izin)",
  "Peluk pohon selama 1 menit di tempat umum",
  "Telepon eks dan bertanya kabar",
  "Beri rating 5 bintang untuk restoran terdekat di Google Maps",
  "Minta pendapat orang tentang baju yang kamu pakai",
  "Nyanyi lagu untuk kasir/minimarket",
  "Telepon saudara dan bicara dengan aksen berbeda",
  "Beri bunga ke orang random (bunga imajiner)",
  "Minta tolong orang bantu mengambil foto",
  "Bercerita tentang hari burukmu ke stranger (aman)",
  "Telepon teman kerja dan bilang besok libur",
  "Beri senyuman ke 10 orang asing",
  "Minta maaf ke seseorang yang pernah kamu sakiti",
  "Berterima kasih ke 3 orang yang pernah membantumu",
  "Telepon guru/dosen favorit dan bilang terima kasih",
  "Beri hadiah kecil ke orang di sebelahmu",
  "Minta nasihat kehidupan ke orang paling tua di ruangan",
  "Berikan motivasi ke seseorang yang sedang sedih",
  "Telepon sahabat dan katakan 'Aku menghargaimu'",
  "Beri tepuk tangan untuk diri sendiri di depan umum",
  "Minta izin foto makanan orang lain di restoran",
  "Bercakap-cakap dengan tanaman selama 2 menit",
  "Telepon customer service dan bilang 'good job'",
  "Beri standing ovation untuk acara TV yang sedang ditonton",
  "Minta resep masakan ke ibu/ayah via telepon",
  "Beri selamat kepada seseorang tanpa alasan jelas",
  "Telepon teman dan berpura-pura salah sambung",
  "Beri nama pada benda mati di sekitarmu",
  "Minta pendapat tentang rambutmu ke orang asing",
  "Berbicara dengan cermin selama 3 menit",
  "Telepon restoran dan pesan makanan aneh",
  "Beri salam ke setiap orang yang lewat selama 5 menit",
  "Minta diajari skill baru ke seseorang",
  "Berteriak 'Hari ini indah!' di tempat sepi",
  "Telepon teman dan minta dibuatkan lagu",
  "Beri penampilan stand up comedy mini ke keluarga",
  "Minta kritik membangun tentang dirimu",
  "Beri pidato singkat tentang pentingnya sendal",
  "Telepon seseorang dan bacakan puisi",
  "Beri pelukan ke orang terdekat (dengan izin)",
  "Minta diajari bahasa isyarat dasar",
  "Berbicara dengan hewan peliharaan (atau imajiner)",
  "Telepon radio dan request lagu lawas",
  "Beri semangat ke diri sendiri di depan cermin"
];
const dare = getRandom(dares)
await Gurita.sendMessage(m.chat, {text: `hai ${m.pushName}, tantangan kamu adalah: \n${dare}`}, {quoted : m})
}
handler.cmd = ['dare']
handler.nama = "dare"
handler.on = "fun"
handler.help = "dare"
module.exports = handler