const handler = async (Gurita, m) => {
    if (!m.isGroup) return m.reply("hanya bisa digunakan di grup")
    function getRandom(arr) {
  const randomIndex = Math.floor(Math.random() * arr.length);
  return arr[randomIndex];
}
const truth = [
  // Kategori Romantic & Relationship (1-50)
  "Siapa orang pertama yang kamu sukai?",
  "Pernahkah kamu mencuri perhatian pacar teman?",
  "Berapa banyak orang yang pernah kamu cium?",
  "Pernahkah kamu jatuh cinta pada guru/dosen?",
  "Siapa mantan yang paling membuatmu patah hati?",
  "Apa alasan terburuk yang pernah kamu gunakan untuk putus?",
  "Pernahkah kamu selingkuh?",
  "Berapa lama hubungan terpanjangmu?",
  "Pernahkah kamu pacaran hanya karena kasihan?",
  "Siapa orang terakhir yang kamu stalk di media sosial?",
  "Pernahkah kamu naksir teman sekelas/kantor?",
  "Apa hal paling romantis yang pernah kamu lakukan?",
  "Pernahkah kamu ditolak saat mengaku cinta?",
  "Usia berapa pertama kali pacaran?",
  "Pernahkah kamu ghosting seseorang?",
  "Apa yang paling kamu cari dalam pasangan?",
  "Pernahkah kamu masih mencintai mantan?",
  "Berapa kali kamu pacaran dalam hidupmu?",
  "Pernahkah kamu mencium orang yang tidak dikenal?",
  "Aplikasi kencan apa yang pernah kamu gunakan?",
  "Pernahkah kamu kencan buta?",
  "Siapa selebriti yang ingin jadi pasanganmu?",
  "Pernahkah kamu menulis surat cinta?",
  "Apa hal paling kekanak-kanakan dalam hubungan?",
  "Pernahkah kamu membandingkan pasangan dengan mantan?",
  "Usia ideal menurutmu untuk menikah?",
  "Ingin punya berapa anak?",
  "Pernahkah kamu memendam perasaan pada teman?",
  "Apa dealbreaker dalam hubungan?",
  "Pernahkah kamu berbohong tentang perasaanmu?",
  "Lebih memilih dicintai atau mencintai?",
  "Pernahkah kamu menolak seseorang dengan kasar?",
  "Apa impian pernikahan idealmu?",
  "Pernahkah kamu merusak hubungan orang lain?",
  "Apa pelajaran terbesar dari hubungan sebelumnya?",
  "Pernahkah kamu stalk mantan pacar?",
  "Lebih suka single atau dalam hubungan?",
  "Pernahkah kamu cemburu buta?",
  "Apa yang akan kamu lakukan jika pasanganmu selingkuh?",
  "Pernahkah kamu berbohong tentang status hubungan?",
  "Siapa orang yang paling ingin kamu ajak kencan di sini?",
  "Pernahkah kamu memiliki crush pada teman sekamarmu?",
  "Apa kencan terburuk yang pernah kamu alami?",
  "Pernahkah kamu pura-pura tidak melihat seseorang?",
  "Lebih memilih cinta atau uang?",
  "Pernahkah kamu tertarik pada saudara teman?",
  "Apa yang pertama kali kamu perhatikan dari lawan jenis?",
  "Pernahkah kamu mencium seseorang di klub malam?",
  "Apa pendapatmu tentang pacaran beda agama?",
  
  // Kategori Personal & Secrets (51-100)
  "Apa rahasia yang belum pernah kamu beri tahu siapa pun?",
  "Pernahkah kamu mencuri?",
  "Apa kebohongan terbesar dalam hidupmu?",
  "Pernahkah kamu dirawat di rumah sakit?",
  "Apa trauma masa kecilmu?",
  "Pernahkah kamu berbohong kepada orang tua?",
  "Apa ketakutan terbesarmu?",
  "Pernahkah kamu kabur dari rumah?",
  "Apa mimpi buruk yang sering kamu alami?",
  "Pernahkah kamu berbohong tentang latar belakang keluarga?",
  "Apa hal paling memalukan tentang dirimu?",
  "Pernahkah kamu memiliki penyakit serius?",
  "Apa hal yang paling kamu sesali?",
  "Pernahkah kamu ditangkap polisi?",
  "Apa fantasi terliarmu?",
  "Pernahkah kamu melakukan sesuatu yang ilegal?",
  "Apa fetish tersembunyimu?",
  "Pernahkah kamu berbohong tentang pendidikan?",
  "Apa rahasia keluarga yang kamu simpan?",
  "Pernahkah kamu terlibat perkelahian?",
  "Apa hal yang membuatmu merasa bersalah?",
  "Pernahkah kamu ditipu?",
  "Apa rahasia pekerjaanmu?",
  "Pernahkah kamu menyakiti orang dengan sengaja?",
  "Apa pencapaian terbesarmu yang tidak diketahui orang?",
  "Pernahkah kamu gagal dalam sesuatu yang penting?",
  "Apa bakat tersembunyimu?",
  "Pernahkah kamu mengalami depresi?",
  "Apa impian yang kamu pendam?",
  "Pernahkah kamu berbohong tentang usia?",
  "Apa rahasia tentang fisikmu?",
  "Pernahkah kamu memalsukan tanda tangan?",
  "Apa kebiasaan buruk yang kamu sembunyikan?",
  "Pernahkah kamu menghilangkan sesuatu yang penting?",
  "Apa rahasia keuanganmu?",
  "Pernahkah kamu memata-matai seseorang?",
  "Apa kelemahan terbesarmu?",
  "Pernahkah kamu berbohong tentang keterampilan?",
  "Apa rahasia tentang masa lalumu?",
  "Pernahkah kamu menjadi korban bullying?",
  "Apa rahasia kesehatanmu?",
  "Pernahkah kamu berbohong tentang pengalaman?",
  "Apa hal paling egois yang pernah kamu lakukan?",
  "Pernahkah kamu menyembunyikan identitas?",
  "Apa rahasia tentang orientasimu?",
  "Pernahkah kamu berbohong tentang gaji?",
  "Apa rahasia tentang keyakinanmu?",
  "Pernahkah kamu memiliki catatan kriminal?",
  "Apa hal paling berisiko yang pernah kamu lakukan?",
  
  // Kategori Friendship & Social (101-150)
  "Pernahkah kamu berbohong kepada teman terbaik?",
  "Siapa teman yang paling kamu iri?",
  "Pernahkah kamu menyebarkan gosip?",
  "Siapa yang paling kamu percaya?",
  "Pernahkah kamu memanfaatkan teman?",
  "Siapa teman yang pernah kamu khianati?",
  "Pernahkah kamu pura-pura sakit untuk menghindari pertemuan?",
  "Siapa yang paling sering kamu pinjam uang?",
  "Pernahkah kamu membicarakan teman di belakang?",
  "Siapa yang paling ingin kamu jadikan sahabat?",
  "Pernahkah kamu iri dengan kehidupan teman?",
  "Siapa teman yang menurutmu toxic?",
  "Pernahkah kamu memilih-milih teman?",
  "Siapa yang paling kamu kagumi?",
  "Pernahkah kamu mencuri pacar teman?",
  "Siapa teman yang paling berbeda denganmu?",
  "Pernahkah kamu mengucilkan seseorang?",
  "Siapa yang paling sering kamu curhati?",
  "Pernahkah kamu berbohong tentang pertemanan?",
  "Siapa yang paling ingin kamu jauhi?",
  "Pernahkah kamu membuat akun palsu untuk stalk seseorang?",
  "Siapa teman yang paling kamu percaya dengan rahasiamu?",
  "Pernahkah kamu membantu teman melakukan hal buruk?",
  "Siapa yang pertama kali kamu hubungi saat bahagia?",
  "Pernahkah kamu menertawakan teman?",
  "Siapa yang paling sering meminjam barang darimu?",
  "Pernahkah kamu meminjam barang tanpa izin?",
  "Siapa teman yang paling pelit?",
  "Pernahkah kamu berbohong untuk melindungi teman?",
  "Siapa yang paling royal?",
  "Pernahkah kamu memutuskan pertemanan?",
  "Siapa teman masa kecil yang masih kamu ingat?",
  "Pernahkah kamu diam saat teman dibully?",
  "Siapa yang paling sering membantu masalahmu?",
  "Pernahkah kamu pamer kepada teman?",
  "Siapa teman yang paling kamu hormati?",
  "Pernahkah kamu memalsukan alasan untuk teman?",
  "Siapa yang paling kamu sayangi selain keluarga?",
  "Pernahkah kamu berbohong tentang kehidupan sosialmu?",
  "Siapa teman yang paling berpengaruh dalam hidupmu?",
  "Pernahkah kamu menjauhi teman karena status sosial?",
  "Siapa yang paling sering kamu ajak jalan?",
  "Pernahkah kamu mengkhianati kepercayaan teman?",
  "Siapa teman yang paling kamu rindukan?",
  "Pernahkah kamu menyimpan dendam pada teman?",
  "Siapa yang paling kamu percaya dengan pinjaman uang?",
  "Pernahkah kamu memilih teman berdasarkan penampilan?",
  "Siapa teman yang paling kamu kagumi karakternya?",
  "Pernahkah kamu merasa kesepian di antara teman-teman?",
  
  // Kategori Work & School (151-200)
  "Pernahkah kamu mencontek saat ujian?",
  "Apa nilai terburuk yang pernah kamu dapat?",
  "Pernahkah kamu memalsukan tanda tangan orang tua?",
  "Siapa guru yang paling tidak kamu sukai?",
  "Pernahkah kamu bolos sekolah/kuliah?",
  "Apa hukuman terberat yang pernah kamu terima?",
  "Pernahkah kamu menyontek pekerjaan teman?",
  "Siapa teman sekelas yang paling kamu sukai?",
  "Pernahkah kamu berbohong tentang IPK/nilai?",
  "Apa mata pelajaran yang paling kamu benci?",
  "Pernahkah kamu menyogok guru/dosen?",
  "Siapa yang paling sering membantu tugasmu?",
  "Pernahkah kamu mencuri jawaban ujian?",
  "Apa prestasi terbesarmu di sekolah?",
  "Pernahkah kamu memalsukan sertifikat?",
  "Siapa guru favoritmu?",
  "Pernahkah kamu terlambat dengan alasan palsu?",
  "Apa kenangan terburuk di sekolah?",
  "Pernahkah kamu menipu dalam kompetisi?",
  "Siapa saingan terbesarmu di sekolah?",
  "Pernahkah kamu berbohong tentang pekerjaan?",
  "Apa kesalahan terbesar di tempat kerja?",
  "Pernahkah kamu mengambil kredit kerja orang lain?",
  "Siapa rekan kerja yang paling menyebalkan?",
  "Pernahkah kamu berbohong dalam CV?",
  "Apa gaji yang sebenarnya kamu inginkan?",
  "Pernahkah kamu datang terlambat dengan alasan palsu?",
  "Siapa bos yang paling kamu takuti?",
  "Pernahkah kamu tidur saat bekerja?",
  "Apa pekerjaan sampingan yang kamu sembunyikan?",
  "Pernahkah kamu mengundurkan diri tanpa pemberitahuan?",
  "Siapa kolega yang pernah kamu sukai?",
  "Pernahkah kamu memanipulasi data kerja?",
  "Apa rahasia tentang perusahaanmu?",
  "Pernahkah kamu berbohong tentang pengalaman kerja?",
  "Siapa yang paling sering kamu mintai bantuan kerja?",
  "Pernahkah kamu mengambil cuti sakit padahal sehat?",
  "Aapa ambisi karir tersembunyimu?",
  "Pernahkah kamu berbohong tentang deadline?",
  "Siapa mentor terbaik dalam karirmu?",
  "Pernahkah kamu menolak pekerjaan karena gengsi?",
  "Apa kebohongan terbesar di tempat kerja?",
  "Pernahkah kamu menghindari tanggung jawab?",
  "Siapa yang ingin kamu jadikan atasan?",
  "Pernahkah kamu memfitnah rekan kerja?",
  "Apa pekerjaan impianmu yang sebenarnya?",
  "Pernahkah kamu menerima suap?",
  "Siapa pesaing terberatmu di kantor?",
  "Pernahkah kamu menyalahgunakan wewenang?",
  "Apa rencana karir rahasiamu?",
  
  // Kategori Habits & Lifestyle (201-250)
  "Apa kebiasaan buruk yang masih kamu lakukan?",
  "Berapa jam kamu tidur sehari?",
  "Pernahkah kamu kecanduan sesuatu?",
  "Apa rutinitas pagi yang aneh?",
  "Pernahkah kamu diet ekstrem?",
  "Berapa banyak uang yang kamu habiskan untuk hobi?",
  "Apa kebiasaan makan yang aneh?",
  "Pernahkah kamu memakan makanan kadaluarsa?",
  "Berapa lama kamu mandi?",
  "Apa ritual sebelum tidurmu?",
  "Pernahkah kamu tidak mandi lebih dari 3 hari?",
  "Berapa banyak ponsel yang pernah kamu rusak?",
  "Apa aplikasi yang paling sering kamu buka?",
  "Pernahkah kamu menghabiskan uang untuk hal tidak penting?",
  "Berapa banyak kartu kredit yang kamu punya?",
  "Apa barang termahal yang pernah kamu beli?",
  "Pernahkah kamu meminjam uang untuk gaya hidup?",
  "Berapa banyak utang yang kamu punya?",
  "Apa pemborosan terbesar dalam hidupmu?",
  "Pernahkah kamu menjual barang demi uang?",
  "Berapa banyak tabungan rahasiamu?",
  "Apa investasi terburuk yang pernah kamu lakukan?",
  "Pernahkah kamu berjudi?",
  "Berapa banyak alkohol yang bisa kamu minum?",
  "Apa makanan yang bisa kamu makan setiap hari?",
  "Pernahkah kamu mencoba narkoba?",
  "Berapa banyak rokok yang kamu hisap sehari?",
  "Apa rutinitas olahragamu?",
  "Pernahkah kamu menyontek dalam game?",
  "Berapa jam sehari kamu main game?",
  "Apa film yang paling sering kamu tonton ulang?",
  "Pernahkah kamu plagiat konten?",
  "Berapa banyak akun media sosial palsu?",
  "Apa konten yang paling sering kamu tonton?",
  "Pernahkah kamu menghabiskan waktu untuk stalk mantan?",
  "Berapa banyak chat yang belum kamu balas?",
  "Apa barang yang selalu kamu bawa?",
  "Pernahkah kamu tidur dengan pakaian luar?",
  "Berapa banyak pasangan sepatu yang kamu punya?",
  "Apa merk fashion favoritmu?",
  "Pernahkah kamu membeli barang bajakan?",
  "Berapa banyak tato yang kamu punya?",
  "Apa bagian tubuh yang ingin kamu ubah?",
  "Pernahkah kamu melakukan operasi plastik?",
  "Berapa berat badan idealmu?",
  "Apa olahraga yang paling kamu benci?",
  "Pernahkah kamu mengikuti tren yang tidak kamu suka?",
  "Berapa banyak buku yang kamu baca setahun?",
  "Apa skill yang ingin kamu pelajari?",
  "Pernahkah kamu berbohong tentang kemampuanmu?",
  
  // Kategori Embarrassing & Funny (251-300)
  "Pernahkah kamu kentut di depan umum?",
  "Apa hal paling memalukan di sekolah?",
  "Pernahkah kamu terjebak di toilet?",
  "Siapa yang pernah melihatmu telanjang?",
  "Pernahkah kamu mengompol saat dewasa?",
  "Apa momen paling canggung dengan mantan?",
  "Pernahkah kamu salah memanggil nama pacar?",
  "Kapan terakhir kali kamu menangis?",
  "Pernahkah kamu jatuh di depan banyak orang?",
  "Apa panggilan paling memalukan yang pernah kamu dapat?",
  "Pernahkah kamu tersesat di mal?",
  "Siapa selebriti yang pernah kamu tiru?",
  "Pernahkah kamu salah mengirim chat?",
  "Apa kostum paling aneh yang pernah kamu pakai?",
  "Pernahkah kamu tertidur di tempat umum?",
  "Kapan terakhir kali kamu muntah karena mabuk?",
  "Pernahkah kamu berantem dengan hewan peliharaan?",
  "Apa lelucon paling buruk yang pernah kamu lakukan?",
  "Pernahkah kamu tersangkut di jendela?",
  "Siapa yang pernah melihat kamu menari sendirian?",
  "Pernahkah kamu salah masuk kamar?",
  "Apa tarian paling aneh yang kamu kuasai?",
  "Pernahkah kamu ketahuan mengupil?",
  "Kapan terakhir kali kamu buang air di celana?",
  "Pernahkah kamu tertawa sendirian di tempat ramai?",
  "Apa suara aneh yang bisa kamu buat?",
  "Pernahkah kamu teriak tanpa alasan?",
  "Siapa yang pernah melihat kamu berfantasi?",
  "Pernahkah kamu berbicara sendiri di depan cermin?",
  "Apa mimpi basah terliarmu?",
  "Pernahkah kamu ketahuan melihat konten dewasa?",
  "Kapan terakhir kali kamu tidak sengaja mengirim foto private?",
  "Pernahkah kamu salah mengenali orang?",
  "Apa kesalahan pengucapan paling memalukan?",
  "Pernahkah kamu membual tentang sesuatu yang tidak bisa kamu lakukan?",
  "Siapa yang pernah melihat kamu tanpa make up?",
  "Pernahkah kamu pingsan di depan umum?",
  "Apa pose selfie paling norakmu?",
  "Pernahkah kamu menabrak sesuatu saat jalan?",
  "Kapan terakhir kali kamu tersedak makanan?",
  "Pernahkah kamu menari di atas meja?",
  "Apa barang paling aneh yang pernah kamu beli?",
  "Pernahkah kamu tersangkut di lift?",
  "Siapa yang pernah menyelamatkan kamu dari situasi memalukan?",
  "Pernahkah kamu lupa nama seseorang yang penting?",
  "Apa hadiah paling buruk yang pernah kamu terima?",
  "Pernahkah kamu salah memakai baju?",
  "Kapan terakhir kali kamu terpeleset?",
  "Pernahkah kamu menangis di bioskop?",
  "Apa cita-cita paling aneh saat kecil?"
];
const hasil = getRandom(truth);
await Gurita.sendMessage(m.chat, {text: `hai ${m.pushName}. ini adalah pertanyaan untuk kamu :\n${hasil}`}, {quoted:m})
}
handler.cmd = ['truth']
handler.nama = "truth"
handler.on = "fun"
handler.help = "truth"
module.exports = handler